name: Enforce Branch Naming Convention

on:
  create:
    branches:
      - '*'

jobs:
  enforce-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|hotfix|release)/.* ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            exit 1
          fi
