name: Python CI Pipeline

on:
  push:
    branches:
      - '**'  # This triggers the pipeline on a push to any branch
  pull_request:
    branches:
      - '**'  # This triggers the pipeline on any pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest tests/main_screen_tests.py

      # Step 5: Upload test results (optional, if you want test artifacts)
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: tests/reports
